namespace UberAPI.Helper
{
    public static class DataPool
    {
        public static readonly IEnumerable<string> NamePool = new List<string>() // Display Name Pool
        {
            "John",
            "Luke",
            "Elias",
            "Rick",
            "Luis",
            "Richard",
            "Aaron",
            "Robert",
            "Ben",
            "Micheal",
            "Mark",
            "Nathan",
            "Kimberly",
            "Cecilia",
            "Eydie",
            "Jordan",
            "Emily",
            "Kylie",
            "Tania",
            "Dylan",
            "Aina",
            "Morgan",
            "Olivia",
            "Reena",
            "Jeremy",
            "Oliver",
            "Reda",
            "Neven",
            "Matthew",
            "Ryan",
            "Amith",
            "Luke",
            "Zahira",
            "Juan",
            "Ahmed",
            "Carlos",
            "Ming",
            "Allen",
            "Anthony"
        };
    }
}
