/*
 * Uber API
 *
 * Uber Mock Api Specification
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = UberAPI.Client.Client.FileParameter;
using OpenAPIDateConverter = UberAPI.Client.Client.OpenAPIDateConverter;
using System.Reflection;

namespace UberAPI.Client.Model
{
    /// <summary>
    /// RequestEstimateResponse
    /// </summary>
    [JsonConverter(typeof(RequestEstimateResponseJsonConverter))]
    [DataContract(Name = "RequestEstimateResponse")]
    public partial class RequestEstimateResponse : AbstractOpenAPISchema, IEquatable<RequestEstimateResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RequestEstimateResponse" /> class
        /// with the <see cref="EstimateWithSurge" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of EstimateWithSurge.</param>
        public RequestEstimateResponse(EstimateWithSurge actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RequestEstimateResponse" /> class
        /// with the <see cref="EstimateWithoutSurge" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of EstimateWithoutSurge.</param>
        public RequestEstimateResponse(EstimateWithoutSurge actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(EstimateWithSurge))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(EstimateWithoutSurge))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: EstimateWithSurge, EstimateWithoutSurge");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `EstimateWithSurge`. If the actual instance is not `EstimateWithSurge`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of EstimateWithSurge</returns>
        public EstimateWithSurge GetEstimateWithSurge()
        {
            return (EstimateWithSurge)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `EstimateWithoutSurge`. If the actual instance is not `EstimateWithoutSurge`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of EstimateWithoutSurge</returns>
        public EstimateWithoutSurge GetEstimateWithoutSurge()
        {
            return (EstimateWithoutSurge)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RequestEstimateResponse {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, RequestEstimateResponse.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of RequestEstimateResponse
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of RequestEstimateResponse</returns>
        public static RequestEstimateResponse FromJson(string jsonString)
        {
            RequestEstimateResponse newRequestEstimateResponse = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newRequestEstimateResponse;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(EstimateWithSurge).GetProperty("AdditionalProperties") == null)
                {
                    newRequestEstimateResponse = new RequestEstimateResponse(JsonConvert.DeserializeObject<EstimateWithSurge>(jsonString, RequestEstimateResponse.SerializerSettings));
                }
                else
                {
                    newRequestEstimateResponse = new RequestEstimateResponse(JsonConvert.DeserializeObject<EstimateWithSurge>(jsonString, RequestEstimateResponse.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("EstimateWithSurge");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into EstimateWithSurge: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(EstimateWithoutSurge).GetProperty("AdditionalProperties") == null)
                {
                    newRequestEstimateResponse = new RequestEstimateResponse(JsonConvert.DeserializeObject<EstimateWithoutSurge>(jsonString, RequestEstimateResponse.SerializerSettings));
                }
                else
                {
                    newRequestEstimateResponse = new RequestEstimateResponse(JsonConvert.DeserializeObject<EstimateWithoutSurge>(jsonString, RequestEstimateResponse.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("EstimateWithoutSurge");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into EstimateWithoutSurge: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + matchedTypes);
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newRequestEstimateResponse;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as RequestEstimateResponse);
        }

        /// <summary>
        /// Returns true if RequestEstimateResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of RequestEstimateResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RequestEstimateResponse input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for RequestEstimateResponse
    /// </summary>
    public class RequestEstimateResponseJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(RequestEstimateResponse).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return RequestEstimateResponse.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
